# Generated by Django 4.1.2 on 2022-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogapplicationcreationmodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapplicationcreationmodel',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
