# Generated by Django 4.1.2 on 2022-11-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0004_alter_blogapplicationcreationmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapplicationcreationmodel',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
