# Generated by Django 4.1 on 2022-11-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_blogapplicationcreationmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapplicationcreationmodel',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
